export const GISCUS_REPO = process.env.NEXT_PUBLIC_GISCUS_REPO;
export const GISCUS_REPOSITORY_ID =
  process.env.NEXT_PUBLIC_GISCUS_REPOSITORY_ID;
export const GISCUS_CATEGORY = process.env.NEXT_PUBLIC_GISCUS_CATEGORY;
export const GISCUS_CATEGORY_ID = process.env.NEXT_PUBLIC_GISCUS_CATEGORY_ID;
