import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Providers } from "@/components/transition/providers";

const ppmoriExtralight = localFont({
  src: "./fonts/PPMori-Extralight.otf",
  variable: "--font-ppmori-extralight",
  weight: "200",
  style: "normal",
});

const ppmoriExtralightItalic = localFont({
  src: "./fonts/PPMori-ExtralightItalic.otf",
  variable: "--font-ppmori-extralight-italic",
  weight: "200",
  style: "italic",
});

const ppmoriRegular = localFont({
  src: "./fonts/PPMori-Regular.otf",
  variable: "--font-ppmori-regular",
  weight: "400",
  style: "normal",
});

const ppmoriRegularItalic = localFont({
  src: "./fonts/PPMori-RegularItalic.otf",
  variable: "--font-ppmori-regular-italic",
  weight: "400",
  style: "italic",
});

const ppmoriSemiBold = localFont({
  src: "./fonts/PPMori-SemiBold.otf",
  variable: "--font-ppmori-semi-bold",
  weight: "600",
  style: "normal",
});

const ppmoriSemiBoldItalic = localFont({
  src: "./fonts/PPMori-SemiBoldItalic.otf",
  variable: "--font-ppmori-semi-bold-italic",
  weight: "600",
  style: "italic",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ppmoriExtralight.variable} ${ppmoriExtralightItalic.variable} ${ppmoriRegular.variable} ${ppmoriRegularItalic.variable} ${ppmoriSemiBold.variable} ${ppmoriSemiBoldItalic.variable} antialiased `}
      >
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
